version: '3'

services:
  monitoring:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8083
      - 8086
      - 3000
    ports:
      - 8083:8083
      - 8086:8086
      - 3000:3000
    command: "./run.sh"