version: '3'

services:
  balancer:
    container_name: balancer-container
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 80:80
    command: "./run.sh"